services:
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
  hotelbooking:
    image: ${DOCKER_REGISTRY-}hotelbooking
    build:
      context: .
      dockerfile: HotelBooking/Dockerfile
  bookingservice:
    image: ${DOCKER_REGISTRY-}bookingservice
    build:
        context: .
        dockerfile: BookingService/Dockerfile
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
     - "6379:6379"
